Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: last_name
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        postalCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: postal_code
        address:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        phoneNumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: phone_number
    lifecycleCallbacks: {  }
